import type { DailyBrief, VideoMeta } from '@/shared/types';

/**
 * 브리프 내보내기 — Markdown, CSV, Gmail 초안, Notion 프렌들리 Markdown.
 *
 * 설계:
 * - Markdown/CSV는 클립보드 또는 다운로드 링크.
 * - Gmail은 mailto:URL에 제목·본문 포함 (편집자·매니저에게 보내기용).
 * - Notion은 OAuth 없이 "Notion-ready Markdown"을 클립보드에 넣어 사용자가 붙여넣음
 *   (OAuth는 L 단계. MVP는 복사-붙여넣기).
 */

export type ExportFormat = 'markdown' | 'csv' | 'gmail' | 'notion';

export interface ExportInput {
  brief: DailyBrief;
  videoIndex: Map<string, VideoMeta>;
  categoryLabel: string;
  format: ExportFormat;
}

export async function exportBrief(input: ExportInput): Promise<string | null> {
  switch (input.format) {
    case 'markdown':
      return copyMarkdown(input);
    case 'csv':
      return downloadCsv(input);
    case 'gmail':
      return openGmailDraft(input);
    case 'notion':
      return copyNotionMarkdown(input);
  }
}

function buildMarkdown(input: ExportInput, style: 'plain' | 'notion'): string {
  const { brief, videoIndex, categoryLabel } = input;
  const lines: string[] = [];
  lines.push(`# ${categoryLabel} — Daily Brief`);
  lines.push('');
  lines.push(`_Generated: ${new Date(brief.generatedAt).toLocaleString()}_`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(brief.summary);
  lines.push('');
  for (const c of brief.clusters) {
    lines.push(`## ${c.label}${c.isGap ? '  — 🔥 Gap' : ''}`);
    lines.push('');
    for (const vid of c.videoIds) {
      const v = videoIndex.get(vid);
      if (!v) continue;
      const views = v.viewCount !== undefined ? ` · ${Intl.NumberFormat('en').format(v.viewCount)} views` : '';
      if (style === 'notion') {
        lines.push(`- [ ] [${v.title}](${v.url})${views}`);
      } else {
        lines.push(`- [${v.title}](${v.url})${views}`);
      }
    }
    lines.push('');
  }
  return lines.join('\n');
}

async function copyMarkdown(input: ExportInput): Promise<string> {
  const md = buildMarkdown(input, 'plain');
  await navigator.clipboard.writeText(md);
  return 'Copied to clipboard as Markdown.';
}

async function copyNotionMarkdown(input: ExportInput): Promise<string> {
  const md = buildMarkdown(input, 'notion');
  await navigator.clipboard.writeText(md);
  return 'Copied as Notion-ready Markdown. Paste into a Notion page.';
}

function downloadCsv(input: ExportInput): string {
  const { brief, videoIndex, categoryLabel } = input;
  const rows: string[][] = [
    ['cluster', 'is_gap', 'title', 'views', 'published_at', 'url'],
  ];
  for (const c of brief.clusters) {
    for (const vid of c.videoIds) {
      const v = videoIndex.get(vid);
      if (!v) continue;
      rows.push([
        c.label,
        c.isGap ? 'yes' : 'no',
        v.title,
        String(v.viewCount ?? ''),
        v.publishedAt,
        v.url,
      ]);
    }
  }
  const csv = rows
    .map((r) => r.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(','))
    .join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `creator-radar-${categoryLabel}-${new Date(brief.generatedAt).toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
  return 'CSV downloaded. Open in Excel or import to Google Sheets.';
}

function openGmailDraft(input: ExportInput): string {
  const { brief, videoIndex, categoryLabel } = input;
  const subject = `${categoryLabel} — Today's brief`;
  const bodyLines: string[] = [];
  bodyLines.push(`${categoryLabel} daily brief (${new Date(brief.generatedAt).toLocaleDateString()})`);
  bodyLines.push('');
  bodyLines.push(brief.summary);
  bodyLines.push('');
  for (const c of brief.clusters) {
    bodyLines.push(`— ${c.label}${c.isGap ? ' (GAP)' : ''} —`);
    for (const vid of c.videoIds) {
      const v = videoIndex.get(vid);
      if (!v) continue;
      bodyLines.push(`• ${v.title}`);
      bodyLines.push(`  ${v.url}`);
    }
    bodyLines.push('');
  }
  bodyLines.push('— Generated by CreatorRadar');
  const url = `https://mail.google.com/mail/?view=cm&fs=1&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(bodyLines.join('\n'))}`;
  window.open(url, '_blank', 'noopener');
  return 'Opened Gmail draft in a new tab.';
}
